# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: cursoPython
      POSTGRES_USER: IsaMan

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
